# Generated by Django 4.1.2 on 2022-10-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('birth_day', models.TextField(verbose_name='Дата рождения')),
                ('death_day', models.TextField(verbose_name='Дата смерти')),
                ('available_books', models.IntegerField(verbose_name='Количество доступных для аренды книг')),
                ('books', models.ManyToManyField(to='books.book', verbose_name='Книги')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
