# Generated by Django 4.1.3 on 2022-11-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
