# Generated by Django 4.1.3 on 2022-11-05 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readers', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_time', models.TextField(verbose_name='Время аренды')),
                ('period', models.TextField(verbose_name='Период аренды')),
                ('fine_size', models.IntegerField(verbose_name='Размер штрафа за день просрочки')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
                ('book_reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.reader', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
    ]
