# Generated by Django 4.1.3 on 2022-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='period',
            field=models.IntegerField(verbose_name='Период аренды'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rent_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время аренды'),
        ),
    ]
