# Generated by Django 4.1.3 on 2022-11-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_alter_rent_period_alter_rent_rent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='period',
            field=models.IntegerField(default=0, verbose_name='Период аренды'),
        ),
    ]
