# Generated by Django 4.1.3 on 2022-11-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readers', '0001_initial'),
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='rents',
            field=models.ManyToManyField(to='rents.rent', verbose_name='Аренды'),
        ),
    ]
