# Generated by Django 4.1.3 on 2022-11-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_alter_rent_period_alter_rent_rent_time'),
        ('readers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='rents',
            field=models.ManyToManyField(null=True, to='rents.rent', verbose_name='Аренды'),
        ),
    ]
