# Generated by Django 4.1.3 on 2022-11-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0004_alter_reader_rents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='fine',
            field=models.IntegerField(default=0, verbose_name='Штраф'),
        ),
    ]
